<?php

/**
 * @file
 * Provides a curso_content entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function curso_content_theme() {
  return [
    'curso_content' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for curso_content templates.
 *
 * Default template: curso-content.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the curso_content information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_curso_content(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
